import { pgTable, text, varchar, integer, decimal, boolean, timestamp, index } from 'drizzle-orm/pg-core'

export const models = pgTable('models', {
  id: text('id').primaryKey(),
  name: varchar('name', { length: 500 }).notNull(),
  slug: varchar('slug', { length: 255 }).notNull().unique(),
  provider: varchar('provider', { length: 255 }).notNull(),
  providerLogo: varchar('provider_logo', { length: 100 }),
  intelligenceIndex: integer('intelligence_index').notNull(),
  codingIndex: decimal('coding_index', { precision: 5, scale: 2 }),
  terminalBenchScore: decimal('terminal_bench_score', { precision: 5, scale: 2 }),
  benchLmCodingScore: decimal('benchlm_coding_score', { precision: 5, scale: 2 }),
  benchLmEvidenceStatus: varchar('benchlm_evidence_status', { length: 30 }),
  benchLmModelName: varchar('benchlm_model_name', { length: 500 }),
  benchLmMatchType: varchar('benchlm_match_type', { length: 20 }),
  aaIntelligenceCostPerTask: decimal('aa_intelligence_cost_per_task', { precision: 10, scale: 4 }),
  terminalBenchCostPerTask: decimal('terminal_bench_cost_per_task', { precision: 10, scale: 4 }),
  deepSweCostPerTask: decimal('deep_swe_cost_per_task', { precision: 10, scale: 4 }),
  codingAgentCostPerTask: decimal('coding_agent_cost_per_task', { precision: 10, scale: 4 }),
  terminalBenchCostPerSuccessfulTask: decimal('terminal_bench_cost_per_successful_task', { precision: 10, scale: 4 }),
  deepSweCostPerSuccessfulTask: decimal('deep_swe_cost_per_successful_task', { precision: 10, scale: 4 }),
  codingAgentCostPerSuccessfulTask: decimal('coding_agent_cost_per_successful_task', { precision: 10, scale: 4 }),
  aaCodingAgentIndex: decimal('aa_coding_agent_index', { precision: 5, scale: 2 }),
  aaCodingAgentCostPerTask: decimal('aa_coding_agent_cost_per_task', { precision: 10, scale: 4 }),
  costPerTask: decimal('cost_per_task', { precision: 10, scale: 4 }),
  inputPricePerM: decimal('input_price_per_m', { precision: 10, scale: 2 }),
  outputPricePerM: decimal('output_price_per_m', { precision: 10, scale: 2 }),
  category: varchar('category', { length: 50 }).notNull(),
  strengths: text('strengths').array(),
  contextWindow: varchar('context_window', { length: 100 }),
  openWeights: boolean('open_weights').default(false),
  speed: integer('speed'),
  latency: decimal('latency', { precision: 10, scale: 2 }),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
}, (table) => ({
  idxCategory: index('idx_models_category').on(table.category),
  idxIntelligence: index('idx_models_intelligence').on(table.intelligenceIndex),
  idxCoding: index('idx_models_coding').on(table.codingIndex),
  idxBenchLmCoding: index('idx_models_benchlm_coding').on(table.benchLmCodingScore),
  idxCost: index('idx_models_cost').on(table.costPerTask),
  idxSlug: index('idx_models_slug').on(table.slug),
}))
