apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-app
spec:
  template:
    spec:
      containers:
        - name: dashboard-app
          # Updated by .github/workflows/commit.nuxt.yaml.
          image: ghcr.io/simonbrundin/dashboard@sha256:5d7b338bc63d494153e1b9d3f7f64a42e53746a55ee40c7790eeee27b5b90f73
          env:
            - name: NODE_ENV
              value: "production"
            - name: NUXT_PUBLIC_APP_URL
              value: "https://dashboard.simonbrundin.com"
            - name: NUXT_MINIMAX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dashboard-auth
                  key: NUXT_MINIMAX_API_KEY
          envFrom:
            - secretRef:
                name: dashboard-uptime-kuma
