apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-app
spec:
  template:
    spec:
      containers:
        - name: dashboard-app
          # Updated by .github/workflows/commit.nuxt.yaml.
          image: ghcr.io/simonbrundin/dashboard@sha256:7da305d65c3c70c06d9d6b6343ba6f5e3c5534404c75aa7241886404779bd0dc
          env:
            - name: NODE_ENV
              value: "production"
            - name: NUXT_PUBLIC_APP_URL
              value: "https://dashboard.simonbrundin.com"
            - name: NUXT_MINIMAX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dashboard-auth
                  key: NUXT_MINIMAX_API_KEY
          envFrom:
            - secretRef:
                name: dashboard-uptime-kuma
