apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-app
spec:
  template:
    spec:
      containers:
        - name: dashboard-app
          # Updated by .github/workflows/commit.nuxt.yaml.
          image: ghcr.io/simonbrundin/dashboard@sha256:3df0727c84524326aa65da8e58eccc0b6dfd3df2a5f3d19a654aee6580520fb8
          env:
            - name: NODE_ENV
              value: "production"
            - name: NUXT_PUBLIC_APP_URL
              value: "https://dashboard.simonbrundin.com"
            - name: NUXT_MINIMAX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: dashboard-auth
                  key: NUXT_MINIMAX_API_KEY
          envFrom:
            - secretRef:
                name: dashboard-uptime-kuma
