apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: dashboard
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: ENC[AES256_GCM,data:u0B3EWLP7T9s7tCTu4GJXvDrTxN3BQoYeI1PD9oAf9DtdsOXY+BG7Gw+bEKsLqhOJiJkU848PdOLUbhD2vmN1PixS3/JdbNpzQARJ348/GrZXslTCY5ySR0KX6pdqsk4TSL+eFaVLF4g,iv:kuNajgufxytQUmhZ2WGlYnb+xsyTMqAwp7lCrHB1HGE=,tag:Ub209nRlxfXfIUH3r5C02g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bEd2MVRpVWZlbnNJNGNy
        RUVKcHYzczByeXc3b0pxNk5Kb0U3TTloOVY0CmVtL3k3TjdFbnNJMGEzRWZRdnl1
        bGZPZERVb0E2cWdRQkdqOG11UVdRSFkKLS0tIG16ODV5V1ZuR3UvRzFUTUpXcE0r
        MDZ3NDk3NVJ0ZzZ2K1NwcjFrcEpXaDgKF5lbTC+Mg9VNbi6iQaPuBkhBjg5+4xjO
        Yaug5u/xqFZpmqBvCi/bqDgmXs1AgCJDMnL2WXFNWV/ydSXeDK8tlw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
  encrypted_regex: ^(stringData|data)$
  lastmodified: "2026-07-30T22:40:42Z"
  mac: ENC[AES256_GCM,data:JPubF/BLWQncocjQAVx6RNxyoV6KlpKVBGvbLHzeSB/1otYbMAyBSzd0hsxq8ijsWRwshSRBqjOlVDEm8poZBbVXpbnKleOZ86e01mwTt9oVWFvQG/lPYlzNiXbLWUKXWvhj/0MTo3SMbgb7EAPCtywKF3t3DbH8iGtCGuKe2JI=,iv:NFxvAFGoLue7c27ZgZDGENSgtPk7jAt5OxGHxnen7cA=,tag:nKU22z4Mh8ZQhFrx9+Rx3Q==,type:str]
  version: 3.13.3
