apiVersion: v1
kind: Secret
metadata:
  name: dashboard-github
  namespace: dashboard
stringData:
  NUXT_GITHUB_USERNAME: ENC[AES256_GCM,data:Uxt0olrKNLx60Iza,iv:1ppCcgR6E9yrttrzuqPHD0EDo/aa/mxZeW1HhpfvHsQ=,tag:IzFQB/xWVn4JLgo9gbFioQ==,type:str]
  NUXT_GITHUB_TOKEN: ENC[AES256_GCM,data:NLrmjxdbAaw3SZnKBNxK5VylGrQIZ3QgcHqbmJhn+ch8O7S6rhDzlw==,iv:VsYYfGOU068PO6CGMdocjkF6m3kQ+z/QcCoSwD0Ckj0=,tag:GGyeZRkZSFGq4CQvYc5NFA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyS0JsRDk4MHlHQ1hOWFBB
        ZENrMDZvcGV4ZERIWnFzWVdIMXgwMFBHVm1BCnk0ZTN3dVFNdnJ1WW1TU040M0JH
        Q0hlQ2VISUZkeENMcWZsMFQ3dk81eUUKLS0tIGhqSDVyL0Y1WEE1elRibW1McWdw
        QVFiZVJqK2F1MURXdDlHenl0YlZOZ0EKEI+aejnEiRhweVAi1mdSoEIZ7xzg4gmY
        r2ZBsM86Cl5gHqlUtZUeKQCTj8qOZrlpVXeEOPqHNxaruwskDESzew==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T20:22:36Z"
  mac: ENC[AES256_GCM,data:vykPY5VGv/as64z12LEGxLZGOzVKW+OBRCtuAy7C81B6WZ+WeJij/9FbMPWCh8x/4dvyStSaGBSs0wDPrTzLXKb1/PAWTpBvHktwWQc6fiEsuTeVjYXbiYiWViurw8G9NYoweIZPlYJg6FpE398v7b1IkOa/YMcTiaVniLXVcbs=,iv:CehkrQhmvVYJcL2Sf521vIwTZYtiXrOnpDQ9ewYnb0A=,tag:RmBqqCzbEq6ZUNWGTipbcQ==,type:str]
  version: 3.13.3
