apiVersion: v1
kind: Secret
metadata:
  name: dashboard-uptime-kuma
  namespace: dashboard
stringData:
  NUXT_UPTIME_KUMA_URL: ENC[AES256_GCM,data:WUOS3IUU9hYcaJiQXk6Hf+vyJoVIjcZCoCQfWDWj2g==,iv:pzv8eeV5EbsS4Z+zXDZ5CzE2R1mCMzbUc40SMxnCu8Q=,tag:YCQi0ZrfNqM+EEQ92EasCw==,type:str]
  NUXT_UPTIME_KUMA_API_KEY: ENC[AES256_GCM,data:XKkzDVepYhc7diG5Ilkw5ldsqeDckDZwF8UI7Brj53bnx+cOwYp1nS+ogUA=,iv:DCr1h5luBAmt7OhaKaXnxMM+2jWBEJmDJEaHmDEyjs4=,tag:5VlBR16+d5tKRSEIanSHuw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRnRTc3ZzcTdmMlJDRnFQ
        UFJ1TkpHK3ZFczNGa1gwVTlrMkJpd0pwMXhrCjQ1VVZGRi96NXgraGpwNCtuSHdT
        aTVWeGE1YXlQL2lFakhXRmRrNktOWTQKLS0tIGt6SXVROWhtQ1BWQkJGMjRyd1Y4
        TWxhTUdPKzI4Z1ZERlptRC81aWtxZmMKrPjUpPeWzj0W0yXJYHCjMbrTQoA4ES5y
        Chpjtn/d0idKoSZp3bejZP9B2pw5KF/+Rc9Fbtj9rgiaRDkHDW3K0A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-31T07:51:16Z"
  mac: ENC[AES256_GCM,data:u7KefHZYnucHkZ7apHGXF3mbJ/D4xsr5W14aHX99gOrihW3O/OdeCdkGH+hdakTz0hfe9Y0Qq/jW8U8PNvM6Jm+o9LcgtJjBg68MrObZdUVeoGNlM4YUdAGZQNvHsjjENhE1NbxyrOYdolu/41P6XC2JVnjrFqh9yhMY0wwn6+Y=,iv:dCitkB5nrl/wQnYr4lINChJ1NCv7gKwKvR2aSC0h8dU=,tag:fp7XHnnZISk/3poByW7ZpQ==,type:str]
  version: 3.13.3
