apiVersion: v1
data:
    NUXT_UPTIME_KUMA_API_KEY: dWsxXzNRQXdLVkpRYWtNVW96bW9rN2M4X2FvdzgyVkJHVll4ME41eUMteHU=
    NUXT_UPTIME_KUMA_URL: aHR0cHM6Ly91cHRpbWUuc2ltb25icnVuZGluLmNvbQ==
kind: Secret
metadata:
    name: dashboard-uptime-kuma
    namespace: dashboard
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMdWMydUk5WFRodmplaUg5
            dEI1Mjdsbm03c29DSHlDTkRPQzRWMkVQVUFnCjVJRnZNUEN6aGgyQVpBVkJWQlor
            NXZWRm1IRVRxUVovU21NSlYvZ29aYUEKLS0tIGRXMzNpWEh5K2lXMk4xT1RsSDZy
            K20xWUV0SWNZRk1halcrRmM0K1dRTkEKiD4ewwrH311Ea53CZexTd9NaCOmKT9d+
            OcmyLvTFCxR8qNnV7+RdllH09cZRkDced/1ly/yUnu1dHVrUzXXGOQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mv3yrgdtqddlr5v9tg67nydvztm3sm6r3uu3j9zhdp736p0wt5gqwyj9lt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T07:41:28Z"
    mac: ENC[AES256_GCM,data:LVvR41wUpJ63ayAIJtJyOX9KzC5P0LYbVKvwCZwMcUPMKnoQMgLdQNBT1CSf0yjptYIU5ZhlpOi78hkqL2m4QI3qJithDfymcSmoO9X6W+uep80sdn0uKkxe8wku+fhHUkVLrZ0rLMtFSGjVUENrveU6hB6RI80twr0AgLAI1BE=,iv:UFIYb6QMqllcUfVhqn3JFVqna0nfV69DzHx5mw1wurM=,tag:LHA6AooIrNLElEI/LKWxVw==,type:str]
    version: 3.13.3
