apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-flux-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dashboard-flux-reader
subjects:
  - kind: ServiceAccount
    name: dashboard
    namespace: dashboard
